export const navigations = [
  {
    name: "Dashboard",
    description: "Lorem ipsum dolor sit.",
    type: "",
    icon: "i-Bar-Chart",
    path: "/dashboard/v1",
    type: "link",
  },
  {
    name: "Media Sosial",
    description: "Lorem ipsum dolor sit.",
    type: "dropDown",
    icon: "i-Video",
    path: "/dashboard/v2",
    type: "link",

  },
  {
    name: "Test",
    description: "Lorem ipsum dolor sit.",
    type: "dropDown",
    icon: "i-Video",
    path: "/dashboard/v56",
    type: "link",

  },
  {
    name: "Medan Satu Data",
    description: "Lorem ipsum dolor sit.",
    type: "dropDown",
    icon: "i-Library",
    sub: [
      {
        icon: "i-Clock-3",
        name: "Medan Satu Data",
        path: "/dashboard/v3",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Admin Kota Medan",
        path: "/dashboard/v4",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Pariwisata",
        path: "/dashboard/v5",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
        path: "/dashboard/v6",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Badan Kesatuan Bangsa dan Politik",
        path: "/dashboard/v7",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Badan Riset dan Inovasi Daerah",
        path: "/dashboard/v8",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Perpustakaan dan Kearsipan",
        path: "/dashboard/v9",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Badan Penanggulangan Bencana Daerah",
        path: "/dashboard/v10",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Badan Kepegawaian dan Pengembangan Sumber Daya Manusia",
        path: "/dashboard/v11",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Pemadam Kebakaran dan Penyelamatan",
        path: "/dashboard/v12",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Pendidikan dan Kebudayaan",
        path: "/dashboard/v13",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Kesehatan",
        path: "/dashboard/v14",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Ketahanan Pangan, Pertanian, dan Perikanan",
        path: "/dashboard/v15",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Pemuda dan Olahraga",
        path: "/dashboard/v16",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Satuan Polisi Pramong Praja",
        path: "/dashboard/v17",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Sosial",
        path: "/dashboard/v18",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Ketenagakerjaan",
        path: "/dashboard/v19",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "RSUD Dr.Pirngadi",
        path: "/dashboard/v20",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Kependudukan dan Pencatatan Sipil",
        path: "/dashboard/v21",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Lingkungan Hidup",
        path: "/dashboard/v22",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Sumber Daya Air Bina Marga dan Bina Konstruksi",
        path: "/dashboard/v23",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Perumahan, Kawasan Permukiman, Cipta Karya dan Tata Ruang",
        path: "/dashboard/v24",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Ketahanan Pangan Pertanian dan Perikanan",
        path: "/dashboard/v25",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Pemberdayaan Perempuan Perlindungan Anak, Pemberdayaan  Masyarakat dan Pengendalian Penduduk dan Keluarga Berencana",
        path: "/dashboard/v26",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Badan Pendapatan Daerah Kota Medan",
        path: "/dashboard/v27",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Koperasi, Usaha Kecil, Menengah, Perindustrian, dan Perdagangan",
        path: "/dashboard/v28",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Dinas Perhubungan",
        path: "/dashboard/v29",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Dinas Komunikasi dan Informatika",
        path: "/dashboard/v30",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Badan Perencanaan Pembangunan Daerah",
        path: "/dashboard/v31",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Badan Keuangan dan Aset Daerah",
        path: "/dashboard/v32",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Inspektorat",
        path: "/dashboard/v33",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Sekretariat DPRD",
        path: "/dashboard/v34",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Amplas",
        path: "/dashboard/v35",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Area",
        path: "/dashboard/v36",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Barat",
        path: "/dashboard/v37",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Baru",
        path: "/dashboard/v38",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Deli",
        path: "/dashboard/v39",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Denai",
        path: "/dashboard/v40",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Helvetia",
        path: "/dashboard/v41",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Johor",
        path: "/dashboard/v42",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Kota",
        path: "/dashboard/v43",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Labuhan",
        path: "/dashboard/v44",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Maimun",
        path: "/dashboard/v45",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Marelan",
        path: "/dashboard/v46",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Perjuangan",
        path: "/dashboard/v47",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Petisah",
        path: "/dashboard/v48",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Polonia",
        path: "/dashboard/v49",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Selayang",
        path: "/dashboard/v50",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Sunggal",
        path: "/dashboard/v51",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Tembung",
        path: "/dashboard/v52",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Timur",
        path: "/dashboard/v53",
        type: "link",
      },
      {
        icon: "i-Clock-3",
        name: "Kecamatan Medan Tuntungan",
        path: "/dashboard/v54",
        type: "link",
      },
      {
        icon: "i-Clock-4",
        name: "Kecamatan Medan Belawan",
        path: "/dashboard/v55",
        type: "link",
      },
    ],
  },
];
